#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the Athena monorepo.
# Installs the pinned toolchain (Bun + PostgreSQL 16), a local Postgres
# cluster, workspace dependencies, dev env files, and the DB schema.
# Safe to run repeatedly and against cached/snapshot state.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export DEBIAN_FRONTEND=noninteractive
PG_BIN="/usr/lib/postgresql/16/bin"
PGDATA="$HOME/pgdata"
PGSOCK="$HOME/pgsock"

# --- 1. Bun (pinned to package.json's packageManager version) ---------------
if [ ! -x "$HOME/.bun/bin/bun" ] && ! command -v bun >/dev/null 2>&1; then
  echo "[install] Installing Bun 1.3.5..."
  curl -fsSL https://bun.sh/install | bash -s "bun-v1.3.5"
fi
export PATH="$HOME/.bun/bin:$PATH"

# --- 2. PostgreSQL 16 -------------------------------------------------------
if [ ! -x "$PG_BIN/postgres" ]; then
  echo "[install] Installing PostgreSQL 16..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql-16 postgresql-client-16
fi
export PATH="$PG_BIN:$PATH"

# --- 3. Local Postgres cluster (owned by the runtime user) ------------------
mkdir -p "$PGSOCK"
if [ ! -f "$PGDATA/PG_VERSION" ]; then
  echo "[install] Initializing Postgres cluster at $PGDATA..."
  initdb -D "$PGDATA" -U postgres --auth-local=trust --auth-host=trust >/dev/null
  {
    echo "port = 5432"
    echo "listen_addresses = 'localhost'"
    echo "unix_socket_directories = '$PGSOCK'"
  } >> "$PGDATA/postgresql.conf"
fi

# Start Postgres just long enough to provision the database + schema.
if ! pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
  pg_ctl -D "$PGDATA" -l "$HOME/pg.log" -w start
fi
for _ in $(seq 1 30); do
  psql -U postgres -h localhost -p 5432 -tc "SELECT 1" >/dev/null 2>&1 && break
  sleep 1
done
psql -U postgres -h localhost -p 5432 -c "ALTER USER postgres WITH PASSWORD 'postgres';" >/dev/null 2>&1 || true
psql -U postgres -h localhost -p 5432 -tc "SELECT 1 FROM pg_database WHERE datname='payload_db'" | grep -q 1 \
  || psql -U postgres -h localhost -p 5432 -c "CREATE DATABASE payload_db;" >/dev/null

# --- 4. Workspace dependencies ----------------------------------------------
echo "[install] Installing workspace dependencies..."
bun install --frozen-lockfile

# --- 5. Local dev env files (never clobber existing) ------------------------
# PREVIEW_SECRET / REVALIDATE_SECRET must be byte-identical across both apps.
if [ ! -f apps/cms/.env ] || [ ! -f apps/web/.env ]; then
  echo "[install] Generating dev env files..."
  PREVIEW_SECRET="$(openssl rand -hex 16)"
  REVALIDATE_SECRET="$(openssl rand -hex 16)"
  PAYLOAD_SECRET="$(openssl rand -hex 24)"
fi
if [ ! -f apps/cms/.env ]; then
  cat > apps/cms/.env <<EOF
# Local development env (generated by .cursor/install.sh; gitignored)
POSTGRES_URL=postgres://postgres:postgres@localhost:5432/payload_db
PAYLOAD_SECRET=${PAYLOAD_SECRET}
CMS_URL=http://localhost:3000
WEB_URL=http://localhost:4321
PREVIEW_SECRET=${PREVIEW_SECRET}
REVALIDATE_SECRET=${REVALIDATE_SECRET}
BLOB_READ_WRITE_TOKEN=
DEPLOY_ENV=development
EOF
fi
if [ ! -f apps/web/.env ]; then
  cat > apps/web/.env <<EOF
# Local development env (generated by .cursor/install.sh; gitignored)
CMS_URL=http://localhost:3000
WEB_URL=http://localhost:4321
PREVIEW_SECRET=${PREVIEW_SECRET}
REVALIDATE_SECRET=${REVALIDATE_SECRET}
PAYLOAD_API_KEY=
EOF
fi

# --- 6. Database schema ------------------------------------------------------
# Only invoke Payload migrate when there are unapplied migrations. This keeps
# re-runs fast and avoids the advisory-lock wait that would occur if a Payload
# dev server were already running against the same database.
MIGRATION_FILES="$(find apps/cms/src/migrations -maxdepth 1 -name '*.ts' ! -name 'index.ts' | wc -l | tr -d ' ')"
APPLIED="$(psql -U postgres -h localhost -p 5432 -d payload_db -tAc \
  "SELECT count(*) FROM payload_migrations" 2>/dev/null || echo 0)"
if [ "${APPLIED:-0}" -lt "${MIGRATION_FILES:-0}" ]; then
  echo "[install] Applying database migrations ($APPLIED/$MIGRATION_FILES applied)..."
  bun run --filter @athena/cms payload migrate
else
  echo "[install] Schema up to date ($APPLIED applied >= $MIGRATION_FILES files); skipping migrate."
fi

echo "[install] Done."
